export const meetupActionTypes = {
    SET_INITIAL_MEETUPS: 'SET_INITIAL_MEETUPS',
    ADD_NEW_MEETUP: 'ADD_NEW_MEETUP',
    TOGGLE_FAVOURITE: 'TOGGLE_FAVOURITE',
    START_FETCHING: 'START_FETCHING',
    FETCHING_FAILED: 'FETCHING_FAILED'
}